#!/bin/bash

echo "Initializing [REDACTED] project"

cp $REDBUILD/package.info $(pwd)/package.info

cp $REDBUILD/config.mk $(pwd)/config.mk

mkdir -p $(pwd)/resources

echo "[REDACTED] project created"
